image: selenium/hub:3

services:
  - docker:dind

before_script:
  - pip install -r requirements.txt

  - docker run -d --name selenium-hub selenium/hub:3.141.59
  - docker run -d --name chrome --link selenium-hub:hub selenium/node-chrome:3.141.59

test:
  script:
    - pytest --alluredir allure-results tests/
    - allure generate allure-results --clean -o allure-report
  artifacts:
    reports:
      type: "external"
      paths:
        - ./allure-report
