image: python:3.9

services:
  - docker:dind

before_script:
  # Install the required dependencies
  - pip install -r requirements.txt
  # Start the Selenium Hub and Chrome nodes in Docker containers
  - docker run -d --name selenium-hub selenium/hub:3.141.59
  - docker run -d --name chrome --link selenium-hub:hub selenium/node-chrome:3.141.59

test:
  script:
    # Run the tests and generate Allure report
    - pytest --alluredir allure-results tests/
    - allure generate allure-results --clean -o allure-report
  artifacts:
    # Publish the Allure report as an artifact
    reports:
      type: "external"
      paths:
        - ./allure-report
